version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  # api:
  #   restart: always
  #   build: .
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./:/code
  #   depends_on:
  #     - mongo
